# Generated by Django 4.2.13 on 2026-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clusters', models.PositiveSmallIntegerField(default=3)),
                ('min_silhouette_threshold', models.FloatField(default=0.3)),
                ('recalculation_interval_days', models.PositiveSmallIntegerField(default=7)),
                ('min_students_for_clustering', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки алгоритма',
            },
        ),
    ]
